Une façon dont numpy a été construit et qui nous permet de faire des calculs entre un tableau A et tableau B

Cela consiste a étendre les dimensions d'un tableau

In [1]:
import numpy as np

In [5]:
A = np.random.randint(0, 10, [2, 3])
B = np.ones((2, 1))
print(A, "\n" ,B)

[[4 9 4]
 [6 3 5]] 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
A + B

array([[ 5., 10.,  5.],
       [ 7.,  4.,  6.]])