1. Les fonctions

Print une fonction EXEMPLE : f(x) = x²

On utilise l'expression lambda

In [11]:
f = lambda x: x**2 # f(x) = x²
f(3)

9

In [8]:
def e_potentielle(masse, hauteur, g = 3.81):
    E = masse * hauteur * g
    print(E, 'Joules')

e_potentielle(80, 3)

914.4 Joules


In [14]:
def e_potentielle_limite(masse, hauteur, limite, g = 9.81):
    E = masse * hauteur * g
    return E < limite

e_potentielle_limite(50, 10, 6000)
# Return True or False

True

In [7]:
def signe(x):
    if (x>0):
        print(x, 'positif')
    elif x == 0:
        print(x, 'nul')
    else:
        print(x, 'negatif')

signe(-1)
signe(2)

-1 negatif
2 positif


2. Boucles if/else / while / for

In [12]:
for element in range(10, -10, -2):
    signe(element)

10 positif
8 positif
6 positif
4 positif
2 positif
0 nul
-2 negatif
-4 negatif
-6 negatif
-8 negatif


In [13]:
x = 0

while x < 10:
    print(x)
    x += 1

0
1
2
3
4
5
6
7
8
9


In [18]:
def fibonacci(n):
    a = 0
    b = 1
    fib = [a]

    while a < n:
        print(a)
        a, b = b, a+b # OU a = b et b = a+b
        fib.append(a)
    return fib

fibonacci(5)

0
1
1
2
3


[0, 1, 1, 2, 3, 5]

3. Listes / Dictionnaires / Tuples

In [24]:
liste_1 = [1, 4, 2, 7, 35, 84]

liste_3 = []

tuple_1 = (1, 2, 6, 1, 7) # on peut pas modifier un tuple (il utilise moins de mémoire)

prenom = 'Yo'

villes = ['Paris', 'Berlin', 'Londres', 'Bruxelles', 'Moscou']

# premier élement
print(villes[0])
# dernier élément
print(villes[-1])

# Slicing
print(villes[0:5:2])


Paris
Moscou
['Paris', 'Londres', 'Moscou']


In [26]:
if 'Paris' in villes :
    print('oui')
else:
    print('non')

oui


In [28]:
for i in enumerate(villes) : # enumerate va print index ET la valeur
    print(i)

(0, 'Paris')
(1, 'Berlin')
(2, 'Londres')
(3, 'Bruxelles')
(4, 'Moscou')


In [29]:
for a, b, in zip(villes, liste_1): # la boucle fort s'arrêtera là où la liste s'arrête
    print(a, b)

Paris 1
Berlin 4
Londres 2
Bruxelles 7
Moscou 35


In [31]:
traduction = {
        "chien":"dog", # Ne peut y avoir que des keys uniques
        "chat":"cat",
        "souris":"mouse",
        "oiseau":"bird"
        }
traduction

{'chien': 'dog', 'chat': 'cat', 'souris': 'mouse', 'oiseau': 'bird'}

In [32]:
inventaire = {
            "bananes":4153,
            "pommes":5613
            }

dict_3 = {
        "dict_1": traduction,
        "dict_2": inventaire
        }
dict_3

{'dict_1': {'chien': 'dog',
  'chat': 'cat',
  'souris': 'mouse',
  'oiseau': 'bird'},
 'dict_2': {'bananes': 4153, 'pommes': 5613}}

In [38]:
import numpy as np

parametres = {
        "W1": np.random.randn(10, 100),  # tableau numpy d'un réseau de neurones par exemple        "b1": np.random.randn(10, 1),
        "W2": np.random.randn(10, 10),
        "b2": np.random.randn(10, 1)
        }

In [40]:
# Accéder aux valeurs du dict
print(inventaire.values())
# Accéder aux keys du dict
inventaire.keys()

dict_values([4153, 5613])


dict_keys(['bananes', 'pommes'])

In [44]:
# Ajouter une key / value au dict
inventaire['abricots'] = 4922

# Retourne la valeur ou Rien si la key n'existe pas
print(inventaire.get('peches', 1)) # 1 ici est un param est la valeur de sortie par defaut

inventaire

1


{'bananes': 4153, 'pommes': 5613, 'abricots': 4922}

In [45]:
# Retirer cette association de "inventaire" puis Extraire dans une variable
fruits = inventaire.pop('abricots')
# fruits return la valeur d'abricots
inventaire

{'bananes': 4153, 'pommes': 5613}

In [47]:
# Créer un dict entier à partir d'une liste
inventaire.fromkeys(villes, 'default')
# -> return {"Paris": 'defaut', "Londres":'defaut',...}

{'Paris': 'default',
 'Berlin': 'default',
 'Londres': 'default',
 'Bruxelles': 'default',
 'Moscou': 'default'}

In [48]:
for i in inventaire:
    print("Keys are :", i) # print que les keys

for i in inventaire.values(): # ou inventaire.key()
    print("Values are :", i) # print values OR keys

for key, value in inventaire.items():
    print("Keys and values are :", key, value) # print key + value

Keys are : bananes
Keys are : pommes
Values are : 4153
Values are : 5613
Keys and values are : bananes 4153
Keys and values are : pommes 5613


In [51]:
classeur = {
    "positif" : [],
    "negatif" : [],
}

def trier(classeur, nombre):
    if nombre > 0:
        classeur['positif'].append(nombre)
    else:
        classeur['negatif'].append(nombre)
    
    return classeur

trier(classeur, -3)
trier(classeur, 10)

{'positif': [10], 'negatif': [-3]}

4. Liste / Dictionnaire Comprehension

In [52]:
# tous les carrés de 0 à 9
liste_4 = []
for i in range(5):
    liste_4.append(i**2)

print(liste_4)
# return [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [53]:
# Peut être écrit par :
liste_5 = [i**2 for i in range(5)]
print(liste_5)

[0, 1, 4, 9, 16]


In [54]:
# Autre raison pour laquelle on utilise cette méthode
import time
start = time.time()
liste_4 = []
for i in range(5):
    liste_4.append(i**2)
end = time.time()
print(end - start)

0.000997304916381836


In [57]:
import time
start = time.time()
liste_5 = [i**2 for i in range(5)]
end = time.time()
print(end - start)

0.0010039806365966797


In [58]:
# Nested list = liste qui contient d'autre liste
liste_6 = [[i for i in range(2)] for j in range(3)]
print(liste_6) # return [[0, 1], [0, 1], [0, 1]]

[[0, 1], [0, 1], [0, 1]]


In [60]:
dict_4 = {
    "0":"Pierre",
    "1":"Jean",
    "2":"Julie",
    "3":"Sophie",
}

prenoms = ["Pierre", "Jean", "Julie", "Sophie"]

In [61]:
dico = {key:value for key, value in enumerate(prenoms)}
print(dico)

{0: 'Pierre', 1: 'Jean', 2: 'Julie', 3: 'Sophie'}


In [62]:
ages = [24, 62, 12, 23]
dico_2 = {prenom:age for prenom, age in zip(prenoms, ages) if age > 20}
dico_2 

{'Pierre': 24, 'Jean': 62, 'Sophie': 23}

5. Built-In Functions

In [64]:
# Return valeur absolue
x = -3
print("Valur absolue :", abs(x))

# Arrondir une decimal
x = 3.14
print("Arrondir une décimal :", round(x))

# List
liste_7 = [0, 23, 14, -19]
print("Valur max :", max(liste_7)) #23
print("Valur min :",min(liste_7))
print("Longueur list :",len(liste_7))
print("Somme des valeurs :",sum(liste_7))

Valur absolue : 3
Arrondir une décimal : 3
Valur max : 23
Valur min : -19
Longueur list : 4
Somme des valeurs : 18


In [66]:
x = 10
print(type(x)) # -> int
x = str(x)
print(type(x)) # -> str

y = 'yo' # en int(x) pas possible

<class 'int'>
<class 'str'>


In [74]:
x = input("Entrez un nombre")
print(type(x))

<class 'str'>


In [72]:
x = int(input("Entrez un nombre"))

print(type(x))

<class 'int'>


In [77]:
x = 25
ville = 'Paris'
message = "la température est de x degC a ville"
print(message)

message2 = "la température est de {} degC a {}".format(x, ville)
print(message2)

message3 = f"la température est de {x} degC a {ville}"
print(message3)

la température est de x degC a ville
la température est de 25 degC a Paris
la température est de 25 degC a Paris


In [81]:
parametres = {
    "W1": np.random.randn(2, 4),
    "b1": np.zeros((2, 1)),
    "W2": np.random.randn(2, 2),
    "b2": np.zeros((2, 1))
}

for i in range(1, 3):
    print("couche", i)
    print(parametres['W{}'.format(i)]) # ou alors print(parametres["W"+str(i)])

couche 1
[[-0.43866386  0.68755789  1.4068986  -0.81881554]
 [-0.8486589   0.81834754  0.83767362  0.46622359]]
couche 2
[[-0.2173746   0.69479974]
 [-0.75029986 -0.23533684]]


In [82]:
f = open("fichier.txt", 'w')

In [84]:
f.write("bonjour")
f.close()

In [85]:
f = open('fichier.txt', 'r')
f.read()

'bonjour'

In [89]:
with open('fichier.txt', 'w') as f: # pas de close() ferme auto
    for i in range(5):
        f.write("{}^2 = {} \n".format(i, i**2))

In [95]:
carres_pairs = {str(k) : k**2 for k in range(0, 20)}
carres_pairs

{'0': 0,
 '1': 1,
 '2': 4,
 '3': 9,
 '4': 16,
 '5': 25,
 '6': 36,
 '7': 49,
 '8': 64,
 '9': 81,
 '10': 100,
 '11': 121,
 '12': 144,
 '13': 169,
 '14': 196,
 '15': 225,
 '16': 256,
 '17': 289,
 '18': 324,
 '19': 361}